version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          name: Decode Keystore
          command: echo $ENCODED_KEYSTORE | base64 --decode > ${HOME}/keystore.jks
      - run:
          name: Set KEYSTORE environment variable
          command: echo 'export KEYSTORE=${HOME}/keystore.jks' >> $BASH_ENV
      - run:
          name: Build
          command: ./gradlew build